Add ability of years selection
koleary94/Angular-2-Datepicker pull request #52
Opened 2016-12-22 04:21 UTC by ZafarSaeedKhan

replaced gif
bump angular to v2.4.0
bump typescript to v2.1.4

2017-01-25 03:10 UTC, kevinoleary19 requested changes
left some comments @ZafarSaeedKhan . lmk if you need any help!

2017-01-25 03:10 UTC, kevinoleary19 commented on README.md
> +![](./demo/datepicker.gif)
appreciate you updating the gif. at least from my end, I would still want the gif to show the default/mvp behavior of the datepicker, which would just be the input, using all of the internal components (like the awesome new year picker), and default blue color. Don't want to confuse anybody about what html components the library comes with. If it's not too much of a hassle would you be able to change that? if not I can do it on my end it's nbd

2017-01-25 03:10 UTC, kevinoleary19 commented on package.json
> +  "name": "@zafarsaeedkhan/angular2-material-datepicker",
can you change these back plz 😄 ?

2017-01-25 03:10 UTC, kevinoleary19 commented on package.json
> +    "build": "rm -rf lib && node_modules/.bin/ngc -p tsconfig-build.json",
thanks for this!

2017-01-25 03:10 UTC, kevinoleary19 commented on tsconfig-aot.json
> -    "types": [ "es6-shim" ]
curious. why the removal of the `es6-shim`?

2017-01-25 03:10 UTC, kevinoleary19 commented on src/datepicker.component.ts
> +      .grid {
Would really prefer `BEM` naming for classes. nested css and generic names like `.grid` and `.col-1-5` cause conflicts with other libraries, make the css harder to refactor, and often cause visual bugs. We can discuss this more in depth if you want. Open to any counterpoints :)

2017-01-25 03:10 UTC, kevinoleary19 commented on src/datepicker.component.ts
> +  getMonthBackgroundColor(month: number) {
can we type this to return a string `: string`?

2017-01-25 03:10 UTC, kevinoleary19 commented on src/datepicker.component.ts
> +    this.calendarYearRange = {
there's probably a way we can create this range algorithmically instead of hardcoding the values. This will also lend itself towards language internationalization, which is going to be a big priority soon. i'll add more comments below

2017-01-25 03:10 UTC, kevinoleary19 commented on src/datepicker.component.ts
> +  changeYearList(direction: string) {
to prevent hardcoded values, we can split this up into three different functions. One function can be responsible for setting the `calendarYears` and alternative variable to `newYearRange`, `calendarYearBucket`:
``` typescript
// new instance variable
this.calendarYearBucket;

// global constants
const leftBound = 1970;
const itemsInGrid = 20;

setCalendarYearsByBucket(bucket: number): null {
  const newYears = [];
  const startYear = leftBound + (itemsInGrid * bucket)
  for (let i=startYear; i < startYear + itemsInGrid; i++) {
    newYears.push(i);
  }

  this.calendarYearBucket = bucket;
  this.calendarYears = newYears;
}

setCalendarYearsByYear(year: string): null {
  const bucket = floor((year - leftBound) / itemsInGrid); // 1970-1989 => 0, 1990-2009 => 1, etc.
  this.setCalendarYearsByBucket(bucket);
}
```

This will allow us to be able to easily reset and change the `calendarYears` upon `year` change.

Then we can create an intermediary (basically slightly modifying the function below and renaming it) between clicking on the arrows and setting the calendarYears data:

```typescript
onYearsChange(direction: string): null {
  if (direction === 'left' && this.calendarYearBucket - 1 >= 0) {
    this.triggerAnimation(direction);
    this.setCalendarYearsByBucket(this.calendarYearBucket - 1);
    ...
  } ... {
  ...
}
```
this sort of a rough draft, so feel free to edit variable names and stuff, but I think it's a good direction to go down. It basically converts the grouping of years into a step function.

2017-01-25 03:10 UTC, koleary94 commented on src/validation.ts
> +export interface ValidationResult {
👍

2017-01-25 03:11 UTC, koleary94 commented
also forgot to mention, @ZafarSaeedKhan  you're going to have to rebase off of master. sorry about that. there were a few overlapping prs open at the same time. thanks for your help! :)

2017-01-28 16:21 UTC, ronydj commented
waiting for this PR =)

2017-02-03 17:29 UTC, zskhan commented
@koleary94 Thanks for the change request but I am currently busy and unable to extract time for this so I will update it ASAP for me.

2017-02-03 17:31 UTC, zskhan commented
@ronydj you can use this package ng-material-datepicker because it will take some time to for me to correct the PR.

2017-02-05 04:11 UTC, koleary94 commented
@zskhan no problem! i'll make the changes and merge. thanks again!

2017-02-05 04:14 UTC, koleary94 commented
@zskhan would you be able to give me write access to the pr? [here's an explanation](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on how to do that if you don't know already

2017-02-07 04:24 UTC, zskhan commented
hey @koleary94!
Maintainers of this repo are already allowed to update my PR.
Can you confirm?

2021-04-12 15:54 UTC, closed without merging